# Site settings
title: LeetCode Daily Challenge
description: Daily LeetCode problems solved automatically
author: scavienger
email: your-email@example.com
baseurl: ""
url: "https://scavienger.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Timezone
timezone: Asia/Seoul

# Permalink structure
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true

# Header navigation
header_pages:
  - archive.md
  - difficulties.md
  - tags.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "scavienger"
